### ISSUE TITLE
Developing a indicator for outfit's new player training.

### ISSUE THREAD

**Issue by GrandNagus** [ps2alerts/website#120]
In the 'outfit' statistics tab(or a new tab), it might be worth listing outfits k/d, kpm and HSR at different level brackets, for example:
BR 0-20
BR 20-25
BR 25-40
BR 40-50
BR 50-75
BR 75-100
BR 100-120

If BR 0-20 is measured you can also control for players which are just on alternate accounts by showing a % of how much players improve on average per bracket.

We have a very basic version of this working here: <https://github.com/blackstardlb/bois-tools>, feel free to yoink the code. The person which developed it no longer plays Planetside, if you want permission message zealous on discord to get you in contact with him.

**Comment by Maelstromeous** [comment]
Will consider this for post release. Not quite sure though the value of this, we're looking more at the outfit level metrics rather than individual players within the outfit context.

**Comment by Maelstromeous** [comment]
I still don't quite get the value of this request, closing.
