### ISSUE TITLE
Remake website/frontend to be standalone js app

### ISSUE THREAD

**Issue by Hailot** [ps2alerts/website#34]
Create a new application from the frameworks CLI, start migrating usuable sections from old project

**Comment by marci4** [comment]
Any specific frameworks in mind?

Maybe Angular?

**Comment by Hailot** [comment]
Personally i prefer Reactjs.. But yeah i think its gonna be Angular, since some of the existing fronted was made i (old) angular.. duo what maelstrome or others think though

**Comment by Maelstromeous** [comment]
The current site is in Angular 1, which is very much deprecated now. Vue seems to be all the rage nowadays and it would be something interesting to learn, using a well known and supported framework.

However our immediate focus should be getting the site functional once more, so while yes we could rewrite it into a new framework, this would be a medium term objective.

**Comment by Maelstromeous** [comment]
Being superceded by #44.
