### ISSUE TITLE
Alert Map feedback integration

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#388]
Upon staging release of the Alert Map feature, we have the following feedback:

- [x] Add capture bar below the "X captured by Y" message below the timeline
- [x] Upon clicking timeline dots, scroll and highlight the cards on the right side
- [x] On desktop, limit zoom out levels to a reasonable value
- [x] Only poll Census for the map_region data once
- [x] Add recenter button
- [x] "Play / pause" button to sequentially go through timeline captures from the beginning
- [x] Fix zoom in sound bug https://discord.com/channels/708061542649954315/708064580223631432/964193484334583898
- [x] Minor: Timeline dot misalignment https://cdn.discordapp.com/attachments/708064580223631432/964197372441813123/Screenshot_2022-04-14_at_17.15.43.png

**Comment by ryanjsims** [comment]
Task 4 may not be related to the AlertMap itself, see my reply at https://discord.com/channels/708061542649954315/708064580223631432/970856958645137429
