### ISSUE TITLE
The Capture History section needs a change.

### ISSUE THREAD

**Issue by AntDX316** [ps2alerts/website#402]
button text = Show Defended instead of Show Defences* 
the text below the button = Show Defended means when the base capture timer started, but resecured before capture. Outfit shows the owner of the base and not what outfit had the most points during the base defence. 

Having those 2 changes would squash all potential for it being seen wrong.

![image](https://user-images.githubusercontent.com/34279421/166661306-f26623d0-73ab-40d8-b412-c8e45c296ddb.png)

**Comment by Maelstromeous** [comment]
Dup of #401.
