### ISSUE TITLE
Settle on technologies and framework to be used for the website

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#44]
The current website is in Angular 1, which is very very old. I was also very new to creating SPAs and JavaScript in general back then, however the design of the website still continues to hold to today's standards, mostly.

I suggest we gut the innards of the site and start that part again, however attempting to keep the design and feel of the site relatively intact, maybe with a few UX considerations.

To discuss August 20th, please offer your suggestions here in the meantime.

**Comment by Maelstromeous** [comment]
@ps2alerts/website-wizards Please offer your input to what technologies we should use :)

**Comment by NotThatBowser** [comment]
Regarding front-end frameworks:

**Svelte**
I'm keen on Svelte but it's newer/less known with all the issues that can bring for a larger project. It's super lightweight both in size, performance and coding, but it's more of a learning curve compared to the 'known' frameworks. Not particularly popular yet and newer also means less help available, so probably not suitable for the project unless everyone happens to already know and like it.

**Flutter Web**
I really like Flutter and it would allow sharing almost all code between web and mobile app (with native performance) but it's still got some issues on web (in late beta) and it requires using Dart (which itself is pretty neat, but means one more thing to learn/setup). I'm experienced with Flutter but evidently I haven't been able to spare time so I couldn't lead on it. Has a learning curve. Same conclusion as above unless mobile is particularly important.

**React**
React works, is mature, and many devs know it - it feels like a default at this point. I don't believe there's inherent web-mobile code sharing with React Native like there is with Flutter but I'm not particularly familiar (so correct me if that's wrong) - only relevant if mobile app is important. The popularity alone (dev familiarity, extensive help resources, etc) probably make it suitable for the project as it's more likely someone will already have some experience with it. Someone more familiar will have to chip in on its real-world flaws.

**Vue**
Not familiar with it, but it's popular enough that it should probably be considered.

**Angular**
My understanding is that this has fallen out of favour for various reasons.

**Comment by microwavekonijn** [comment]
Personally I would go with Vue as I have more experience with it to the point where I can write more advanced plugins. I think Vue is an excellent choice as it is easy to setup with all modern features(e.g. server-side-rendering, SPA, lazy-loading, components). That said React is also a very good choice though it will be more work. Svelte I think is too bare-bone. Angular I see as more or less the same as Vue. And I have never really heard about Flutter.

Also I want to propose Tailwinds as a CSS framework. Unlike Bootstrap and Bulma, which are component based, Tailwind is a utility based framework that is really flexible. As our layout is not that standard Tailwind allows us to do everything without the need to write any css ever.

**Comment by zhenghung** [comment]
React would be my pick, but only because it's really the only front-end javascript framework I've used before, but not enough that I'd consider myself a wizard. It also has an expansive collection of UI component libraries. Regardless, I'm up for learning something new if everyone finds another framework more preferable.

**Comment by Maelstromeous** [comment]
Framework now confirmed as **VueJS**. @microwavekonijn is to set up the initial framework for the website and collaborators will then hopefully flesh it out.
