### ISSUE TITLE
Fix eslint

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#462]
Eslint checks are failing, we should fix them to ensure code quality.

**Comment by oslohes123** [comment]
@Maelstromeous 
I am noticing on the actions that eslint is trying to format .json files and .scss files is this correct? I thought eslint was only for the java style files

**Comment by Maelstromeous** [comment]
@oslohes123 usually its only meant to cover vue and scss files but it can also do other things. If it's covering the ps2alerts-constants folder for example we need to exclude it. I've not done any investigation towards this yet so I don't know what's wrong as of yet

**Comment by Maelstromeous** [comment]
Fixed in a922456ea72887a32d86f72f0abb21535d4947f9
