### ISSUE TITLE
Inclusion of a production server

### ISSUE THREAD

**Issue by microwavekonijn** [ps2alerts/website#49]
The dev environment uses Vue cli for serving the app to a browser, however this will not do for production. As simple node or nginx server is needed to serve the app. A requirement could be that the app should be server side rendered, but it is not that important as most search engines are optimized to index SPA's nowadays.

**Comment by Maelstromeous** [comment]
@microwavekonijn can you point me to some documentation on how to do this for Vue?

**Comment by microwavekonijn** [comment]
Mostly the a static file server that has all the compile files, but where every url that doesn't point to a file is routed to the base html instance.

https://cli.vuejs.org/guide/deployment.html#docker-nginx
https://ssr.vuejs.org/
