### ISSUE TITLE
Dahaka Pump actually has a connection to Dahaka Southern Post now I think.

### ISSUE THREAD

**Issue by AntDX316** [ps2alerts/website#546]
![image](https://user-images.githubusercontent.com/34279421/215654071-9e7909d0-f04e-442a-b8ee-8222d74005f6.png)
![image](https://user-images.githubusercontent.com/34279421/215653898-920d5442-fb8a-460c-8d92-0cf6a28cd4bd.png)
![image](https://user-images.githubusercontent.com/34279421/215654027-5f0131a4-52d2-4247-befe-4af03437fcc9.png)

It has a connection because I went there and capped it but on the website it doesn't show it does. Should update the lattice lines for all maps to todays date.

**Comment by Maelstromeous** [comment]
Fixed in https://github.com/ps2alerts/website/pull/556
