### ISSUE TITLE
Implement version based caching

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#59]
One topic I'm really struggling to find an answer for from Google is how to properly serve assets with a random / injected hash in order for  browsers to cache correctly versioned CSS / JS. Right now it's just being loaded like:

`/app.js`

Which may not change between versions after it's first loaded as browsers cache that path.

Ideally, it needs to be with a random sha / hash on it, so it turns into this:

`/app-aeeh24.js`

This will then mean all assets are fresh and correct. Ideal situation would be to inject the build SHA which is already available to Vue enviroment via injection from GitHub actions.

**Comment by microwavekonijn** [comment]
Do it like Laravel mix. Just md5 the current unix timestamp and append it as a get variable to the url.

**Comment by microwavekonijn** [comment]
https://webpack.js.org/guides/caching/
https://stackoverflow.com/questions/39238163/how-can-i-make-webpack-use-a-cache-busting-suffix
