### ISSUE TITLE
Implement browser desktop notifications

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#7]
https://www.sitepoint.com/introduction-web-notifications-api/

Would be brilliant for the user to sign up to which notifications they want to receive when they have the site open (can save their settings to local storage) and show the HTML 5 notification shade when a new alert starts.

**Comment by marci4** [comment]
Do you want to use WebPush to receive the notification when the website is not loaded or just notification with some background jobs if the site is visible?

**Comment by Maelstromeous** [comment]
There's plenty of bots out there to notify the user. We probably dont' need this.
