### ISSUE TITLE
Global statistics filters

### ISSUE THREAD

**Issue by Mauti404** [ps2alerts/website#72]
Iterating on [this issue](https://github.com/ps2alerts/website/issues/31)

We could use statistics computed by several parameters like :

- Server
- Continent
- Dates
- Alert start time

So that we could compute like win rate on Miller on Esamir in the past year during prime time.

**Comment by Maelstromeous** [comment]
Hi @marci4 ,

Could you please expand this issue and detail exactly what you're looking to see on the site, from what you're saying it's stuff I'm already going to include on the stats page via filtering via brackets, dates, continents etc.

> Esamir in the past year during prime time.

Note, the data will only exist from Jan 1st 2021, it is not possible to backdate it.

**Comment by Maelstromeous** [comment]
@Mauti404 ping

**Comment by Mauti404** [comment]
Compute the amount of wins for a warpgate or a faction depending from parameter (like date range, server, continent, hour).

**Comment by Maelstromeous** [comment]
This is now done.
