### ISSUE TITLE
Improve initial site load UX.

### ISSUE THREAD

**Issue by NotThatBowser** [ps2alerts/website#81]
While the site is loading for the first time you currently get a white splash page for a brief moment.

To make the loading feel more seamless, the body's background could be changed to a similar colour as the site's background graphics, e.g. `#3f3f3f` which is a middle tone of the background tile's shades.

https://github.com/ps2alerts/website/blob/972d67221661eba83caf992aeedd3ba95f95d234/public/index.html#L23

**Comment by Maelstromeous** [comment]
Thanks, this *should* be fixed with server side rendering coming as part of #80. Keeping this open as a reminder

**Comment by Maelstromeous** [comment]
Fixed in 126ce61, thanks for the report
