### ISSUE TITLE
SCSS extensions / nesting are being purged out of CSS

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#96]
There's some sort of incompatability between SCSS and tailwind purgeCSS which removes all nested CSS classes like this:

```
.btn {
  @apply something;
  &:first-child {
    @apply something-else;
  }
}
```

The first layer (.btn) works fine, anythning nested below it however doesn't get rendered in the final template.

However the below will work when added at the `tailwind.css` file:
```
.btn {
  @apply something;
}
.btn:first-child {
  @apply something-else;
}
```

This is only the case when purgeCSS is enabled in tailwind.

Having to turn purgecss off for now on all envs just to get it to render correctly, which obviously we don't want to be doing as there's a lot of wasted space.

**Comment by Maelstromeous** [comment]
It gets excluded completely.

**Comment by microwavekonijn** [comment]
No I mean without purgecss.

**Comment by Maelstromeous** [comment]
It's fine and works, its certainly something to do with the purge itself

**Comment by microwavekonijn** [comment]
I mean what css do you get?

**Comment by microwavekonijn** [comment]
The thing is
```css
.btn {
  @apply something;
  &:first-child {
    @apply something-else;
  }
}
```
should resolve to
```css
.btn {
  // The stuff from @apply something;
}
.btn:first-child {
  // The stuff from @apply something-else;
}
```
as far as I know. Btw, where is sass configured? I cannot seem to find it

**Comment by Maelstromeous** [comment]
```
.btn-group {
  display: inline-flex
}

.btn-group .btn:first-of-type {
  border-top-left-radius: .25rem;
  border-bottom-left-radius: .25rem
}

.btn-group .btn:last-of-type {
  border-top-right-radius: .25rem;
  border-bottom-right-radius: .25rem
}
``` by the looks of it

**Comment by Maelstromeous** [comment]
It's included into Nuxt here: https://github.com/ps2alerts/website/blob/revive/nuxt.config.js#L85-L87

Then it's additionally included in postcss here: https://github.com/ps2alerts/website/blob/revive/nuxt.config.js#L107

I believe the latter has to be done in order to use imports correctly.

**Comment by microwavekonijn** [comment]
I have the feeling that the order in which sass and tailwind are executed are switched. As in sass first then tailwind, that is when you use tailwind first you get tailwind > prugecss > sass not sass > tailwind > prugecss.

**Comment by Maelstromeous** [comment]
Quite possible. What do you suggest as a solution?

**Comment by Maelstromeous** [comment]
May also explain why the postcss processing times on build are rather
lengthy...

**Comment by microwavekonijn** [comment]
I don't know. I am trying to figure out sass and tailwind in nuxt, but that requires knowledge of webpack which I don't have.

**Comment by Maelstromeous** [comment]
Think this was fixed, not seen it recently. Think it was some sass loader issue. Closing.
